#fromDir: "/Volumes/HD-LCU3 1"
fromDir: "/Volumes/HD-LCU3/yuito_pics"
#toDir: "/Volumes/SSD/pics"
toDir: "/Users/sky0621/Documents/HD-LCU3/pics/yuito_pics"
targetExts: "Pictures"
targetDocumentsExts: [".pdf", ".txt", ".doc", ".docx", ".xls", ".xlsx", ".csv", ".tsv", ".ini", ".ppt", ".pptx", ".xml", ".epub", ".md", ".url"]
targetPicturesExts: [".jpg", ".jpeg", ".png", ".gif", ".avif", ".webp", ".tiff", ".svg", ".bmp", ".psd", ".raw"]
targetMusicsExts: [".mp3", ".wav", ".aiff", ".wma", ".aac"]
targetMoviesExts: [".mp4", ".avi", ".mov", ".webm", ".flv", ".wmv", ".avchd", ".f4v", ".swf", ".mkv"]
rename: true
operation: 9
